FROM debian:bullseye

RUN apt update -y && \
    apt install -y npm openssl

RUN openssl req -x509 -nodes -newkey rsa:4096 -keyout ssl.key -out ssl.crt -days 9999 -subj "/CN=localhost/O=Fake Name/C=US"

RUN mkdir /code

COPY app.js /code

RUN cd /code && npm install express

CMD ["node", "/code/app.js"]
