FROM archlinux:latest

RUN pacman -Syu --noconfirm python-pip openssl git

RUN openssl req -x509 -nodes -newkey rsa:4096 -keyout ssl.key -out ssl.crt -days 9999 -subj "/CN=localhost/O=Fake Name/C=US"

RUN pip install git+https://github.com/nathants/py-util && \
    pip install git+https://github.com/nathants/py-pool && \
    pip install git+https://github.com/nathants/py-web && \
    find -name __pycache__ | xargs rm -rf

COPY app.py /

CMD ["python3", "app.py"]
