FROM archlinux:latest

RUN pacman -Syu --noconfirm python-pip openssl

RUN openssl req -x509 -nodes -newkey rsa:4096 -keyout ssl.key -out ssl.crt -days 9999 -subj "/CN=localhost/O=Fake Name/C=US"

RUN pacman -Syu --noconfirm git

RUN pip install git+https://github.com/nathants/py-util && \
    pip install git+https://github.com/nathants/py-pool && \
    pip install git+https://github.com/nathants/py-web

COPY app.py /

CMD python app.py
