FROM alpine:latest

RUN apk update && \
    apk add python3 openssl git

RUN python3 -m ensurepip

RUN openssl req -x509 -nodes -newkey rsa:4096 -keyout ssl.key -out ssl.crt -days 9999 -subj "/CN=localhost/O=Fake Name/C=US"

RUN python3 -m pip install git+https://github.com/nathants/py-util && \
    python3 -m pip install git+https://github.com/nathants/py-pool && \
    python3 -m pip install git+https://github.com/nathants/py-web

COPY app.py /

CMD ["python3", "app.py"]
